name: Create Archive
on: [push]
jobs:
  make-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: actions/checkout@master
    #- name: Make Zip
     # uses: thedoctor0/zip-release@master
     # with:
     #  filename: 'settings.zip'
      #  exclusions: '*.git* /*node_modules/* .editorconfig *.github* *.zip'
    - name: Upload the config zip
      uses: actions/upload-artifact@v2
      with:
        name: settings.zip
        path: |
              .
              !*.git
              !/*node_modules/*
              !.editorconfig
              !*.github*
              !*.zip
